import{timeOverlaps,clock,distanceKm,geometricMedian}from'./v3-calc.js';
const API='https://jnciddblcndmthmmvqrz.functions.supabase.co/timefit-public';
const $=selector=>document.querySelector(selector);
const code=new URLSearchParams(location.search).get('code')||'';
const saved=localStorage.getItem(`timefit:response:${code}`);
const addText=(parent,tag,text,className='')=>{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;parent.append(node);return node};
const day=value=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${value}T00:00:00`));
const shortTime=value=>String(value||'').slice(0,5);
const toast=message=>{const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1800)};
function renderConfirmed(event){const section=$('#confirmed-section');if(!section||!event.confirmed_date)return;$('#confirmed-time').textContent=`${day(event.confirmed_date)} · ${shortTime(event.confirmed_start_time)}–${shortTime(event.confirmed_end_time)}`;$('#confirmed-place').textContent=event.confirmed_place_name||'';$('#confirmed-address').textContent=event.confirmed_place_address||'주최자가 확정한 장소입니다.';section.classList.remove('hidden')}
function renderTimes(people){const box=$('#times');box.innerHTML='';const options=timeOverlaps(people).slice(0,6);if(!options.length){addText(box,'div','아직 비교할 수 있는 시간 응답이 없습니다.','empty-state');return}options.forEach((option,index)=>{const card=document.createElement('article');card.className=`result-card${index===0?' featured':''}`;addText(card,'div',index===0?'BEST':`OPTION ${index+1}`,'result-rank');addText(card,'div',`${day(option.date)} · ${clock(option.start)}–${clock(option.end)}`,'result-time');const progress=document.createElement('div');progress.className='progress';const bar=document.createElement('span');bar.style.width=`${option.names.length/people.length*100}%`;progress.append(bar);card.append(progress);addText(card,'div',`${option.names.length}명 가능 · ${option.names.join(', ')}`,'result-people');box.append(card)})}
function renderDetails(people){const box=$('#details');box.innerHTML='';if(!people.length){addText(box,'div','아직 응답이 없습니다.','empty-state');return}people.forEach(person=>{const card=document.createElement('article');card.className='result-card';addText(card,'strong',person.display_name);addText(card,'div',person.address||'위치 미입력','result-people');(person.availability||[]).forEach(slot=>addText(card,'div',`${day(slot.date)} ${slot.start}–${slot.end}`,'distance-row'));box.append(card)})}
function renderMap(people){const points=people.filter(person=>Number.isFinite(person.latitude)&&Number.isFinite(person.longitude)).map(person=>({latitude:person.latitude,longitude:person.longitude,name:person.display_name,address:person.address}));const summary=$('#place-summary');if(!points.length||!window.kakao){addText(summary,'div','위치 응답이 아직 없습니다.','empty-state');return}const center=geometricMedian(points);const map=new kakao.maps.Map($('#result-map'),{center:new kakao.maps.LatLng(center.latitude,center.longitude),level:8});const bounds=new kakao.maps.LatLngBounds(),places=new kakao.maps.services.Places();points.forEach(point=>{const position=new kakao.maps.LatLng(point.latitude,point.longitude);new kakao.maps.Marker({map,position,title:point.name});bounds.extend(position)});const choose=rows=>{const candidates=rows.length?rows:[{place_name:'계산된 균형 지점',y:center.latitude,x:center.longitude,address_name:'출발 위치의 기하 중앙값'}];const ranked=candidates.map(item=>{const point={latitude:Number(item.y),longitude:Number(item.x)},distances=points.map(origin=>distanceKm(point,origin));return{item,point,distances,score:Math.max(...distances)*.7+distances.reduce((a,b)=>a+b,0)/distances.length*.3}}).sort((a,b)=>a.score-b.score);const best=ranked[0],position=new kakao.maps.LatLng(best.point.latitude,best.point.longitude);new kakao.maps.Marker({map,position,title:best.item.place_name});bounds.extend(position);map.setBounds(bounds);addText(summary,'div',best.item.place_name,'place-name');addText(summary,'p',best.item.road_address_name||best.item.address_name||'이동 균형이 좋은 지점','result-people');const table=$('#distances');table.innerHTML='';best.distances.forEach((distance,index)=>{const row=document.createElement('div');row.className='distance-row';addText(row,'span',points[index].name);addText(row,'strong',`${distance.toFixed(1)}km`);table.append(row)})};places.categorySearch('SW8',(rows,state)=>choose(state===kakao.maps.services.Status.OK?rows:[]),{location:new kakao.maps.LatLng(center.latitude,center.longitude),radius:10000,sort:kakao.maps.services.SortBy.DISTANCE})}
async function load(){try{const response=await fetch(`${API}?action=event&code=${encodeURIComponent(code)}`);const data=await response.json();if(!response.ok||!data.event)throw 0;const event=data.event,people=data.participants||[],head=$('#result-head');head.innerHTML='';addText(head,'span',event.confirmed_date?'Confirmed meeting':'Live result','eyebrow');addText(head,'h1',event.title);addText(head,'p',event.confirmed_date?'주최자가 최종 일정을 확정했습니다.':`${people.length}명의 최신 응답으로 계산한 결과입니다.`);const meta=document.createElement('div');meta.className='meta-row';[`${event.date_start}–${event.date_end}`,`${event.meeting_duration_minutes||60}분 모임`,event.confirmed_date?'최종 확정':event.status==='open'?'응답 받는 중':'응답 마감'].forEach(value=>addText(meta,'span',value,'meta-pill'));head.append(meta);renderConfirmed(event);renderTimes(people);renderDetails(people);renderMap(people);$('#result-body').classList.remove('hidden');if(event.status!=='open'){$('#respond').textContent=event.confirmed_date?'확정 일정 보기':'응답 마감'}else if(saved)$('#respond').textContent='내 응답 수정';if(new URLSearchParams(location.search).get('saved'))toast('응답을 저장했습니다.')}catch{$('#result-head').textContent='결과를 불러올 수 없습니다.'}}
$('#respond').href=`event.html?code=${encodeURIComponent(code)}`;$('#share-url').value=`${location.origin}/summary.html?code=${encodeURIComponent(code)}`;$('#copy-result').onclick=async()=>{await navigator.clipboard.writeText($('#share-url').value);toast('결과 링크를 복사했습니다.')};load();
